# -*- coding: utf-8 -*-
"""main.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WeaSstSyGkuUoSJ5624ieWKyRubSsVpW
"""

# Week 4: Data Visualization Project

import pandas as pd

# Load dataset
df = pd.read_csv("sales_data.csv")

# Display first 5 rows
print("📌 First 5 rows of the dataset:")
print(df.head())

# Dataset shape
print("\n📊 Dataset Shape (rows, columns):")
print(df.shape)

# Column names
print("\n🧾 Column Names:")
print(df.columns)

# Data types and basic info
print("\nℹ️ Dataset Information:")
print(df.info())

# Basic statistics
print("\n📈 Basic Statistics:")
print(df.describe())

# 🧹 Data Cleaning

# Check missing values
print("\n❓ Missing values before cleaning:")
print(df.isnull().sum())

# Remove duplicate rows
df = df.drop_duplicates()

# Fill missing values with 0 (simple & safe)
df = df.fillna(0)

print("\n✅ Missing values after cleaning:")
print(df.isnull().sum())

# 📊 Data Analysis

total_sales = df['Total_Sales'].sum()
average_sales = df['Total_Sales'].mean()
max_sales = df['Total_Sales'].max()

print("💰 Total Sales:", total_sales)
print("📊 Average Sales:", average_sales)
print("🔥 Highest Sale:", max_sales)

import matplotlib.pyplot as plt

# Sales by Product
sales_by_product = df.groupby('Product')['Total_Sales'].sum()

sales_by_product.plot(kind='bar', title='Sales by Product')

plt.xlabel("Product")
plt.ylabel("Total Sales")
plt.show()

product_sales = df.groupby("Product")["Total_Sales"].sum()
plt.figure(figsize=(6, 6))
plt.pie(
    product_sales,
    labels=product_sales.index,
    autopct='%1.1f%%',
    startangle=140
)

plt.title("Sales Distribution by Product")
plt.show()